'use client';

import React from 'react';

// 365日分の正確なデータ（日付、石名、個別slug、石言葉）
const BIRTHDAY_STONES_DATA = [
  // 1月
  { date: '1月1日', stone: 'ガーネット', slug: 'garnet', meaning: '真実・友愛' },
  { date: '1月2日', stone: 'ローズクォーツ', slug: 'rose-quartz-meaning', meaning: '愛の始まり' },
  { date: '1月3日', stone: 'アメジスト', slug: 'amethyst', meaning: '誠実' },
  { date: '1月4日', stone: 'ムーンストーン', slug: 'moonstone', meaning: '感受性' },
  { date: '1月5日', stone: 'ルビー', slug: 'ruby', meaning: '情熱' },
  { date: '1月6日', stone: 'スモーキークォーツ', slug: 'smoky-quartz', meaning: '安定' },
  { date: '1月7日', stone: 'ラピスラズリ', slug: 'lapis-lazuli', meaning: '真実' },
  { date: '1月8日', stone: 'ガーネット', slug: 'garnet', meaning: '友情' },
  { date: '1月9日', stone: 'アクアマリン', slug: 'aquamarine', meaning: '清澄' },
  { date: '1月10日', stone: 'ブルートパーズ', slug: 'blue-topaz', meaning: '知性・誠実' },
  { date: '1月11日', stone: 'サファイア', slug: 'sapphire', meaning: '品格' },
  { date: '1月12日', stone: 'アイオライト', slug: 'iolite', meaning: '信念' },
  { date: '1月13日', stone: 'ヘマタイト', slug: 'hematite', meaning: '自信・守護' },
  { date: '1月14日', stone: 'ローズクォーツ', slug: 'rose-quartz-meaning', meaning: '愛情' },
  { date: '1月15日', stone: 'アメジスト', slug: 'amethyst', meaning: '心の平和' },
  { date: '1月16日', stone: 'ガーネット', slug: 'garnet', meaning: '持続' },
  { date: '1月17日', stone: 'ターコイズ', slug: 'turquoise', meaning: '幸運・守護' },
  { date: '1月18日', stone: 'カーネリアン', slug: 'carnelian', meaning: '活力' },
  { date: '1月19日', stone: 'ペリドット', slug: 'peridot', meaning: '保護' },
  { date: '1月20日', stone: 'シトリン', slug: 'citrine', meaning: '繁栄' },
  { date: '1月21日', stone: 'オニキス', slug: 'onyx', meaning: '強さ' },
  { date: '1月22日', stone: 'ダイヤモンド', slug: 'diamond', meaning: '純粋' },
  { date: '1月23日', stone: 'ラピスラズリ', slug: 'lapis-lazuli', meaning: '尊厳' },
  { date: '1月24日', stone: 'アベンチュリン', slug: 'aventurine', meaning: '幸運' },
  { date: '1月25日', stone: 'ガーネット', slug: 'garnet', meaning: '忠実' },
  { date: '1月26日', stone: 'スモーキークォーツ', slug: 'smoky-quartz', meaning: '落ち着き' },
  { date: '1月27日', stone: 'クリソプレーズ', slug: 'chrysoprase', meaning: '幸福' },
  { date: '1月28日', stone: 'ルビー', slug: 'ruby', meaning: '生命力' },
  { date: '1月29日', stone: 'タイガーアイ', slug: 'tigers-eye', meaning: '洞察・決断' },
  { date: '1月30日', stone: 'ローズクォーツ', slug: 'rose-quartz-meaning', meaning: '平和' },
  { date: '1月31日', stone: 'ラピスラズリ', slug: 'lapis-lazuli', meaning: '誠実' },

  // 2月
  { date: '2月1日', stone: 'アメジスト', slug: 'amethyst', meaning: '守護・誠実' },
  { date: '2月2日', stone: 'ローズクォーツ', slug: 'rose-quartz-meaning', meaning: '愛情' },
  { date: '2月3日', stone: 'ガーネット', slug: 'garnet', meaning: '友情' },
  { date: '2月4日', stone: 'ムーンストーン', slug: 'moonstone', meaning: '直感' },
  { date: '2月5日', stone: 'ルビー', slug: 'ruby', meaning: '情熱' },
  { date: '2月6日', stone: 'アクアマリン', slug: 'aquamarine', meaning: '清潔・冷静' },
  { date: '2月7日', stone: 'パール', slug: 'pearl', meaning: '純粋' },
  { date: '2月8日', stone: 'サファイア', slug: 'sapphire', meaning: '誠実' },
  { date: '2月9日', stone: 'ペリドット', slug: 'peridot', meaning: '幸運' },
  { date: '2月10日', stone: 'シトリン', slug: 'citrine', meaning: '明るさ' },
  { date: '2月11日', stone: 'タイガーアイ', slug: 'tigers-eye', meaning: '決断力' },
  { date: '2月12日', stone: 'アメジスト', slug: 'amethyst', meaning: '平和' },
  { date: '2月13日', stone: 'ラピスラズリ', slug: 'lapis-lazuli', meaning: '真実' },
  { date: '2月14日', stone: 'ローズクォーツ', slug: 'rose-quartz-meaning', meaning: '愛・ロマンス' },
  { date: '2月15日', stone: 'カーネリアン', slug: 'carnelian', meaning: '行動力' },
  { date: '2月16日', stone: 'ターコイズ', slug: 'turquoise', meaning: '保護' },
  { date: '2月17日', stone: 'スモーキークォーツ', slug: 'smoky-quartz', meaning: '安定' },
  { date: '2月18日', stone: 'アメジスト', slug: 'amethyst', meaning: '誠実' },
  { date: '2月19日', stone: 'アクアマリン', slug: 'aquamarine', meaning: '清澄' },
  { date: '2月20日', stone: 'ダイヤモンド', slug: 'diamond', meaning: '永遠' },
  { date: '2月21日', stone: 'ガーネット', slug: 'garnet', meaning: '忠実' },
  { date: '2月22日', stone: 'ヘマタイト', slug: 'hematite', meaning: '意志' },
  { date: '2月23日', stone: 'エメラルド', slug: 'emerald', meaning: '成長' },
  { date: '2月24日', stone: 'アメジスト', slug: 'amethyst', meaning: '心の平和' },
  { date: '2月25日', stone: 'ルビー', slug: 'ruby', meaning: '強さ' },
  { date: '2月26日', stone: 'オニキス', slug: 'onyx', meaning: '守護' },
  { date: '2月27日', stone: 'ムーンストーン', slug: 'moonstone', meaning: '感受性' },
  { date: '2月28日', stone: 'ターコイズ', slug: 'turquoise', meaning: '幸運' },

  // 3月
  { date: '3月1日', stone: 'アクアマリン', slug: 'aquamarine', meaning: '勇気・知性' },
  { date: '3月2日', stone: 'ローズクォーツ', slug: 'rose-quartz-meaning', meaning: '愛情' },
  { date: '3月3日', stone: 'コーラル（珊瑚）', slug: 'coral', meaning: '幸福・長寿' },
  { date: '3月4日', stone: 'ガーネット', slug: 'garnet', meaning: '友情' },
  { date: '3月5日', stone: 'ムーンストーン', slug: 'moonstone', meaning: '直感' },
  { date: '3月6日', stone: 'サファイア', slug: 'sapphire', meaning: '誠実' },
  { date: '3月7日', stone: 'エメラルド', slug: 'emerald', meaning: '希望' },
  { date: '3月8日', stone: 'アメジスト', slug: 'amethyst', meaning: '平和' },
  { date: '3月9日', stone: 'ブラッドストーン', slug: 'bloodstone', meaning: '勇気' },
  { date: '3月10日', stone: 'アクアマリン', slug: 'aquamarine', meaning: '清澄' },
  { date: '3月11日', stone: 'シトリン', slug: 'citrine', meaning: '明るさ' },
  { date: '3月12日', stone: 'ラピスラズリ', slug: 'lapis-lazuli', meaning: '真実' },
  { date: '3月13日', stone: 'ターコイズ', slug: 'turquoise', meaning: '守護' },
  { date: '3月14日', stone: 'アクアマリン', slug: 'aquamarine', meaning: '知性' },
  { date: '3月15日', stone: 'ペリドット', slug: 'peridot', meaning: '保護' },
  { date: '3月16日', stone: 'ロードナイト', slug: 'rhodonite', meaning: '許し・愛' },
  { date: '3月17日', stone: 'クリソプレーズ', slug: 'chrysoprase', meaning: '幸運' },
  { date: '3月18日', stone: 'フローライト', slug: 'fluorite', meaning: '集中・成長' },
  { date: '3月19日', stone: 'アクアマリン', slug: 'aquamarine', meaning: '新生' },
  { date: '3月20日', stone: 'ダイヤモンド', slug: 'diamond', meaning: '純粋' },
  { date: '3月21日', stone: 'エメラルド', slug: 'emerald', meaning: '成長' },
  { date: '3月22日', stone: 'カーネリアン', slug: 'carnelian', meaning: '活力' },
  { date: '3月23日', stone: 'アクアマリン', slug: 'aquamarine', meaning: '冷静' },
  { date: '3月24日', stone: 'ムーンストーン', slug: 'moonstone', meaning: '感受性' },
  { date: '3月25日', stone: 'ローズクォーツ', slug: 'rose-quartz-meaning', meaning: '愛情' },
  { date: '3月26日', stone: 'ガーネット', slug: 'garnet', meaning: '持続' },
  { date: '3月27日', stone: 'サファイア', slug: 'sapphire', meaning: '品格' },
  { date: '3月28日', stone: 'スモーキークォーツ', slug: 'smoky-quartz', meaning: '安定' },
  { date: '3月29日', stone: 'アクアマリン', slug: 'aquamarine', meaning: '誠実' },
  { date: '3月30日', stone: 'ラピスラズリ', slug: 'lapis-lazuli', meaning: '尊厳' },
  { date: '3月31日', stone: 'ブルートパーズ', slug: 'blue-topaz', meaning: '明晰' },

  // 4月
  { date: '4月1日', stone: 'ダイヤモンド', slug: 'diamond', meaning: '純粋・永遠' },
  { date: '4月2日', stone: 'ローズクォーツ', slug: 'rose-quartz-meaning', meaning: '愛情' },
  { date: '4月3日', stone: 'エメラルド', slug: 'emerald', meaning: '希望' },
  { date: '4月4日', stone: 'サファイア', slug: 'sapphire', meaning: '誠実' },
  { date: '4月5日', stone: 'ガーネット', slug: 'garnet', meaning: '友情' },
  { date: '4月6日', stone: 'アメジスト', slug: 'amethyst', meaning: '平和' },
  { date: '4月7日', stone: 'ルビー', slug: 'ruby', meaning: '情熱' },
  { date: '4月8日', stone: 'ターコイズ', slug: 'turquoise', meaning: '幸運' },
  { date: '4月9日', stone: 'ダイヤモンド', slug: 'diamond', meaning: '不滅' },
  { date: '4月10日', stone: 'ムーンストーン', slug: 'moonstone', meaning: '感受性' },
  { date: '4月11日', stone: 'ペリドット', slug: 'peridot', meaning: '保護' },
  { date: '4月12日', stone: 'アクアマリン', slug: 'aquamarine', meaning: '清澄' },
  { date: '4月13日', stone: 'シトリン', slug: 'citrine', meaning: '繁栄' },
  { date: '4月14日', stone: 'タイガーアイ', slug: 'tigers-eye', meaning: '決断' },
  { date: '4月15日', stone: 'ダイヤモンド', slug: 'diamond', meaning: '強さ' },
  { date: '4月16日', stone: 'ラピスラズリ', slug: 'lapis-lazuli', meaning: '真実' },
  { date: '4月17日', stone: 'ローズクォーツ', slug: 'rose-quartz-meaning', meaning: '優しさ' },
  { date: '4月18日', stone: 'カーネリアン', slug: 'carnelian', meaning: '活力' },
  { date: '4月19日', stone: 'エメラルド', slug: 'emerald', meaning: '発展' },
  { date: '4月20日', stone: 'アベンチュリン', slug: 'aventurine', meaning: '幸運' },
  { date: '4月21日', stone: 'ルビー', slug: 'ruby', meaning: '高潔' },
  { date: '4月22日', stone: 'スモーキークォーツ', slug: 'smoky-quartz', meaning: '安定' },
  { date: '4月23日', stone: 'サファイア', slug: 'sapphire', meaning: '品格' },
  { date: '4月24日', stone: 'ガーネット', slug: 'garnet', meaning: '忠実' },
  { date: '4月25日', stone: 'ダイヤモンド', slug: 'diamond', meaning: '完璧' },
  { date: '4月26日', stone: 'アメジスト', slug: 'amethyst', meaning: '誠実' },
  { date: '4月27日', stone: 'フローライト', slug: 'fluorite', meaning: '成長' },
  { date: '4月28日', stone: 'ムーンストーン', slug: 'moonstone', meaning: '直感' },
  { date: '4月29日', stone: 'ターコイズ', slug: 'turquoise', meaning: '守護' },
  { date: '4月30日', stone: 'エメラルド', slug: 'emerald', meaning: '成長' },

  // 5月
  { date: '5月1日', stone: 'エメラルド', slug: 'emerald', meaning: '希望・幸福' },
  { date: '5月2日', stone: 'ローズクォーツ', slug: 'rose-quartz-meaning', meaning: '愛情' },
  { date: '5月3日', stone: 'ガーネット', slug: 'garnet', meaning: '友情' },
  { date: '5月4日', stone: 'サファイア', slug: 'sapphire', meaning: '誠実' },
  { date: '5月5日', stone: 'エメラルド', slug: 'emerald', meaning: '成長' },
  { date: '5月6日', stone: 'クリソプレーズ', slug: 'chrysoprase', meaning: '幸運' },
  { date: '5月7日', stone: 'ムーンストーン', slug: 'moonstone', meaning: '感受性' },
  { date: '5月8日', stone: 'ペリドット', slug: 'peridot', meaning: '保護' },
  { date: '5月9日', stone: 'エメラルド', slug: 'emerald', meaning: '発展' },
  { date: '5月10日', stone: 'アメジスト', slug: 'amethyst', meaning: '平和' },
  { date: '5月11日', stone: 'ダイヤモンド', slug: 'diamond', meaning: '純粋' },
  { date: '5月12日', stone: 'ルビー', slug: 'ruby', meaning: '情熱' },
  { date: '5月13日', stone: 'エメラルド', slug: 'emerald', meaning: '安定' },
  { date: '5月14日', stone: 'ターコイズ', slug: 'turquoise', meaning: '守護' },
  { date: '5月15日', stone: 'シトリン', slug: 'citrine', meaning: '繁栄' },
  { date: '5月16日', stone: 'エメラルド', slug: 'emerald', meaning: '誠実' },
  { date: '5月17日', stone: 'アクアマリン', slug: 'aquamarine', meaning: '清澄' },
  { date: '5月18日', stone: 'タイガーアイ', slug: 'tigers-eye', meaning: '決断' },
  { date: '5月19日', stone: 'マラカイト', slug: 'malachite', meaning: '変容・守護' },
  { date: '5月20日', stone: 'ラピスラズリ', slug: 'lapis-lazuli', meaning: '真実' },
  { date: '5月21日', stone: 'サファイア', slug: 'sapphire', meaning: '品格' },
  { date: '5月22日', stone: 'エメラルド', slug: 'emerald', meaning: '完璧' },
  { date: '5月23日', stone: 'ローズクォーツ', slug: 'rose-quartz-meaning', meaning: '優しさ' },
  { date: '5月24日', stone: 'ガーネット', slug: 'garnet', meaning: '忠実' },
  { date: '5月25日', stone: 'エメラルド', slug: 'emerald', meaning: '長寿' },
  { date: '5月26日', stone: 'カーネリアン', slug: 'carnelian', meaning: '活力' },
  { date: '5月27日', stone: 'オニキス', slug: 'onyx', meaning: '強さ' },
  { date: '5月28日', stone: 'エメラルド', slug: 'emerald', meaning: '守護' },
  { date: '5月29日', stone: 'スモーキークォーツ', slug: 'smoky-quartz', meaning: '安定' },
  { date: '5月30日', stone: 'ムーンストーン', slug: 'moonstone', meaning: '直感' },
  { date: '5月31日', stone: 'エメラルド', slug: 'emerald', meaning: '成功' },

  // 6月
  { date: '6月1日', stone: 'パール', slug: 'pearl', meaning: '純粋・誠実' },
  { date: '6月2日', stone: 'ムーンストーン', slug: 'moonstone', meaning: '感受性' },
  { date: '6月3日', stone: 'アレキサンドライト', slug: 'alexandrite', meaning: '変化・適応' },
  { date: '6月4日', stone: 'ローズクォーツ', slug: 'rose-quartz-meaning', meaning: '愛情' },
  { date: '6月5日', stone: 'ガーネット', slug: 'garnet', meaning: '友情' },
  { date: '6月6日', stone: 'パール', slug: 'pearl', meaning: '純真' },
  { date: '6月7日', stone: 'サファイア', slug: 'sapphire', meaning: '誠実' },
  { date: '6月8日', stone: 'エメラルド', slug: 'emerald', meaning: '希望' },
  { date: '6月9日', stone: 'パール', slug: 'pearl', meaning: '優雅' },
  { date: '6月10日', stone: 'ターコイズ', slug: 'turquoise', meaning: '守護' },
  { date: '6月11日', stone: 'ムーンストーン', slug: 'moonstone', meaning: '直感' },
  { date: '6月12日', stone: 'アメジスト', slug: 'amethyst', meaning: '平和' },
  { date: '6月13日', stone: 'パール', slug: 'pearl', meaning: '美しさ' },
  { date: '6月14日', stone: 'ルビー', slug: 'ruby', meaning: '情熱' },
  { date: '6月15日', stone: 'ペリドット', slug: 'peridot', meaning: '幸運' },
  { date: '6月16日', stone: 'パール', slug: 'pearl', meaning: '成功' },
  { date: '6月17日', stone: 'ラピスラズリ', slug: 'lapis-lazuli', meaning: '真実' },
  { date: '6月18日', stone: 'シトリン', slug: 'citrine', meaning: '繁栄' },
  { date: '6月19日', stone: 'パール', slug: 'pearl', meaning: '純潔' },
  { date: '6月20日', stone: 'ダイヤモンド', slug: 'diamond', meaning: '永遠' },
  { date: '6月21日', stone: 'ムーンストーン', slug: 'moonstone', meaning: '感性' },
  { date: '6月22日', stone: 'パール', slug: 'pearl', meaning: '品格' },
  { date: '6月23日', stone: 'アクアマリン', slug: 'aquamarine', meaning: '清澄' },
  { date: '6月24日', stone: 'カーネリアン', slug: 'carnelian', meaning: '活力' },
  { date: '6月25日', stone: 'パール', slug: 'pearl', meaning: '幸福' },
  { date: '6月26日', stone: 'タイガーアイ', slug: 'tigers-eye', meaning: '決断' },
  { date: '6月27日', stone: 'オパール', slug: 'opal', meaning: '希望' },
  { date: '6月28日', stone: 'パール', slug: 'pearl', meaning: '友情' },
  { date: '6月29日', stone: 'エメラルド', slug: 'emerald', meaning: '発展' },
  { date: '6月30日', stone: 'ローズクォーツ', slug: 'rose-quartz-meaning', meaning: '愛情' },

  // 7月
  { date: '7月1日', stone: 'ルビー', slug: 'ruby', meaning: '情熱・勝利' },
  { date: '7月2日', stone: 'ローズクォーツ', slug: 'rose-quartz-meaning', meaning: '愛情' },
  { date: '7月3日', stone: 'シトリン', slug: 'citrine', meaning: '繁栄' },
  { date: '7月4日', stone: 'ガーネット', slug: 'garnet', meaning: '友情' },
  { date: '7月5日', stone: 'ルビー', slug: 'ruby', meaning: '高潔' },
  { date: '7月6日', stone: 'サファイア', slug: 'sapphire', meaning: '誠実' },
  { date: '7月7日', stone: 'サファイア', slug: 'sapphire', meaning: '星の加護' },
  { date: '7月8日', stone: 'ルビー', slug: 'ruby', meaning: '情熱' },
  { date: '7月9日', stone: 'ムーンストーン', slug: 'moonstone', meaning: '感受性' },
  { date: '7月10日', stone: 'アメジスト', slug: 'amethyst', meaning: '平和' },
  { date: '7月11日', stone: 'ルビー', slug: 'ruby', meaning: '強さ' },
  { date: '7月12日', stone: 'ペリドット', slug: 'peridot', meaning: '保護' },
  { date: '7月13日', stone: 'ターコイズ', slug: 'turquoise', meaning: '守護' },
  { date: '7月14日', stone: 'ルビー', slug: 'ruby', meaning: '生命力' },
  { date: '7月15日', stone: 'カーネリアン', slug: 'carnelian', meaning: '活力' },
  { date: '7月16日', stone: 'ラピスラズリ', slug: 'lapis-lazuli', meaning: '真実' },
  { date: '7月17日', stone: 'ルビー', slug: 'ruby', meaning: '魅力' },
  { date: '7月18日', stone: 'タイガーアイ', slug: 'tigers-eye', meaning: '決断' },
  { date: '7月19日', stone: 'オニキス', slug: 'onyx', meaning: '強さ' },
  { date: '7月20日', stone: 'ルビー', slug: 'ruby', meaning: '持続' },
  { date: '7月21日', stone: 'ダイヤモンド', slug: 'diamond', meaning: '純粋' },
  { date: '7月22日', stone: 'エメラルド', slug: 'emerald', meaning: '希望' },
  { date: '7月23日', stone: 'ルビー', slug: 'ruby', meaning: '情熱' },
  { date: '7月24日', stone: 'ローズクォーツ', slug: 'rose-quartz-meaning', meaning: '優しさ' },
  { date: '7月25日', stone: 'スモーキークォーツ', slug: 'smoky-quartz', meaning: '安定' },
  { date: '7月26日', stone: 'ルビー', slug: 'ruby', meaning: '友愛' },
  { date: '7月27日', stone: 'アクアマリン', slug: 'aquamarine', meaning: '清澄' },
  { date: '7月28日', stone: 'シトリン', slug: 'citrine', meaning: '明るさ' },
  { date: '7月29日', stone: 'ルビー', slug: 'ruby', meaning: '勝利' },
  { date: '7月30日', stone: 'ムーンストーン', slug: 'moonstone', meaning: '直感' },
  { date: '7月31日', stone: 'ガーネット', slug: 'garnet', meaning: '忠実' },

  // 8月
  { date: '8月1日', stone: 'ペリドット', slug: 'peridot', meaning: '幸運・保護' },
  { date: '8月2日', stone: 'ローズクォーツ', slug: 'rose-quartz-meaning', meaning: '愛情' },
  { date: '8月3日', stone: 'オニキス', slug: 'onyx', meaning: '強さ' },
  { date: '8月4日', stone: 'サファイア', slug: 'sapphire', meaning: '誠実' },
  { date: '8月5日', stone: 'ペリドット', slug: 'peridot', meaning: '守護' },
  { date: '8月6日', stone: 'カーネリアン', slug: 'carnelian', meaning: '活力' },
  { date: '8月7日', stone: 'ダイヤモンド', slug: 'diamond', meaning: '純粋' },
  { date: '8月8日', stone: 'ペリドット', slug: 'peridot', meaning: '成長' },
  { date: '8月9日', stone: 'ルビー', slug: 'ruby', meaning: '情熱' },
  { date: '8月10日', stone: 'エメラルド', slug: 'emerald', meaning: '希望' },
  { date: '8月11日', stone: 'ペリドット', slug: 'peridot', meaning: '発展' },
  { date: '8月12日', stone: 'タイガーアイ', slug: 'tigers-eye', meaning: '決断' },
  { date: '8月13日', stone: 'アメジスト', slug: 'amethyst', meaning: '平和' },
  { date: '8月14日', stone: 'ペリドット', slug: 'peridot', meaning: '友情' },
  { date: '8月15日', stone: 'ターコイズ', slug: 'turquoise', meaning: '守護' },
  { date: '8月16日', stone: 'シトリン', slug: 'citrine', meaning: '繁栄' },
  { date: '8月17日', stone: 'ペリドット', slug: 'peridot', meaning: '幸福' },
  { date: '8月18日', stone: 'ラピスラズリ', slug: 'lapis-lazuli', meaning: '真実' },
  { date: '8月19日', stone: 'ムーンストーン', slug: 'moonstone', meaning: '感受性' },
  { date: '8月20日', stone: 'ペリドット', slug: 'peridot', meaning: '安定' },
  { date: '8月21日', stone: 'ローズクォーツ', slug: 'rose-quartz-meaning', meaning: '優しさ' },
  { date: '8月22日', stone: 'スモーキークォーツ', slug: 'smoky-quartz', meaning: '落ち着き' },
  { date: '8月23日', stone: 'ペリドット', slug: 'peridot', meaning: '誠実' },
  { date: '8月24日', stone: 'アクアマリン', slug: 'aquamarine', meaning: '清澄' },
  { date: '8月25日', stone: 'ガーネット', slug: 'garnet', meaning: '友愛' },
  { date: '8月26日', stone: 'ペリドット', slug: 'peridot', meaning: '成功' },
  { date: '8月27日', stone: 'オパール', slug: 'opal', meaning: '希望' },
  { date: '8月28日', stone: 'ルビー', slug: 'ruby', meaning: '情熱' },
  { date: '8月29日', stone: 'ペリドット', slug: 'peridot', meaning: '持続' },
  { date: '8月30日', stone: 'サファイア', slug: 'sapphire', meaning: '品格' },
  { date: '8月31日', stone: 'カーネリアン', slug: 'carnelian', meaning: '活力' },

  // 9月
  { date: '9月1日', stone: 'サファイア', slug: 'sapphire', meaning: '誠実・品格' },
  { date: '9月2日', stone: 'ローズクォーツ', slug: 'rose-quartz-meaning', meaning: '愛情' },
  { date: '9月3日', stone: 'ラピスラズリ', slug: 'lapis-lazuli', meaning: '真実' },
  { date: '9月4日', stone: 'ガーネット', slug: 'garnet', meaning: '友情' },
  { date: '9月5日', stone: 'サファイア', slug: 'sapphire', meaning: '知恵' },
  { date: '9月6日', stone: 'ムーンストーン', slug: 'moonstone', meaning: '感受性' },
  { date: '9月7日', stone: 'アメジスト', slug: 'amethyst', meaning: '平和' },
  { date: '9月8日', stone: 'サファイア', slug: 'sapphire', meaning: '守護' },
  { date: '9月9日', stone: 'ダイヤモンド', slug: 'diamond', meaning: '純粋' },
  { date: '9月10日', stone: 'エメラルド', slug: 'emerald', meaning: '希望' },
  { date: '9月11日', stone: 'サファイア', slug: 'sapphire', meaning: '高潔' },
  { date: '9月12日', stone: 'シトリン', slug: 'citrine', meaning: '繁栄' },
  { date: '9月13日', stone: 'ターコイズ', slug: 'turquoise', meaning: '幸運' },
  { date: '9月14日', stone: 'サファイア', slug: 'sapphire', meaning: '忠実' },
  { date: '9月15日', stone: 'カーネリアン', slug: 'carnelian', meaning: '活力' },
  { date: '9月16日', stone: 'ペリドット', slug: 'peridot', meaning: '保護' },
  { date: '9月17日', stone: 'サファイア', slug: 'sapphire', meaning: '誠実' },
  { date: '9月18日', stone: 'タイガーアイ', slug: 'tigers-eye', meaning: '決断' },
  { date: '9月19日', stone: 'スモーキークォーツ', slug: 'smoky-quartz', meaning: '安定' },
  { date: '9月20日', stone: 'サファイア', slug: 'sapphire', meaning: '品格' },
  { date: '9月21日', stone: 'ローズクォーツ', slug: 'rose-quartz-meaning', meaning: '優しさ' },
  { date: '9月22日', stone: 'オニキス', slug: 'onyx', meaning: '強さ' },
  { date: '9月23日', stone: 'サファイア', slug: 'sapphire', meaning: '成功' },
  { date: '9月24日', stone: 'アクアマリン', slug: 'aquamarine', meaning: '清澄' },
  { date: '9月25日', stone: 'ガーネット', slug: 'garnet', meaning: '忠実' },
  { date: '9月26日', stone: 'サファイア', slug: 'sapphire', meaning: '知識' },
  { date: '9月27日', stone: 'ルビー', slug: 'ruby', meaning: '情熱' },
  { date: '9月28日', stone: 'ムーンストーン', slug: 'moonstone', meaning: '直感' },
  { date: '9月29日', stone: 'サファイア', slug: 'sapphire', meaning: '誠意' },
  { date: '9月30日', stone: 'ラピスラズリ', slug: 'lapis-lazuli', meaning: '尊厳' },

  // 10月
  { date: '10月1日', stone: 'オパール', slug: 'opal', meaning: '希望・創造' },
  { date: '10月2日', stone: 'ローズクォーツ', slug: 'rose-quartz-meaning', meaning: '愛情' },
  { date: '10月3日', stone: 'トルマリン', slug: 'tourmaline', meaning: '調和' },
  { date: '10月4日', stone: 'ガーネット', slug: 'garnet', meaning: '友情' },
  { date: '10月5日', stone: 'オパール', slug: 'opal', meaning: '幸運' },
  { date: '10月6日', stone: 'サファイア', slug: 'sapphire', meaning: '誠実' },
  { date: '10月7日', stone: 'アメジスト', slug: 'amethyst', meaning: '平和' },
  { date: '10月8日', stone: 'オパール', slug: 'opal', meaning: '変化' },
  { date: '10月9日', stone: 'シトリン', slug: 'citrine', meaning: '繁栄' },
  { date: '10月10日', stone: 'ダイヤモンド', slug: 'diamond', meaning: '純粋' },
  { date: '10月11日', stone: 'オパール', slug: 'opal', meaning: '希望' },
  { date: '10月12日', stone: 'ムーンストーン', slug: 'moonstone', meaning: '感受性' },
  { date: '10月13日', stone: 'ターコイズ', slug: 'turquoise', meaning: '守護' },
  { date: '10月14日', stone: 'オパール', slug: 'opal', meaning: '多彩' },
  { date: '10月15日', stone: 'カーネリアン', slug: 'carnelian', meaning: '活力' },
  { date: '10月16日', stone: 'エメラルド', slug: 'emerald', meaning: '成長' },
  { date: '10月17日', stone: 'オパール', slug: 'opal', meaning: '創造' },
  { date: '10月18日', stone: 'ラピスラズリ', slug: 'lapis-lazuli', meaning: '真実' },
  { date: '10月19日', stone: 'スモーキークォーツ', slug: 'smoky-quartz', meaning: '安定' },
  { date: '10月20日', stone: 'オパール', slug: 'opal', meaning: '個性' },
  { date: '10月21日', stone: 'タイガーアイ', slug: 'tigers-eye', meaning: '決断' },
  { date: '10月22日', stone: 'ローズクォーツ', slug: 'rose-quartz-meaning', meaning: '優しさ' },
  { date: '10月23日', stone: 'オパール', slug: 'opal', meaning: '豊かさ' },
  { date: '10月24日', stone: 'アクアマリン', slug: 'aquamarine', meaning: '清澄' },
  { date: '10月25日', stone: 'ルビー', slug: 'ruby', meaning: '情熱' },
  { date: '10月26日', stone: 'オパール', slug: 'opal', meaning: '感性' },
  { date: '10月27日', stone: 'ペリドット', slug: 'peridot', meaning: '守護' },
  { date: '10月28日', stone: 'ガーネット', slug: 'garnet', meaning: '忠実' },
  { date: '10月29日', stone: 'オパール', slug: 'opal', meaning: '輝き' },
  { date: '10月30日', stone: 'ムーンストーン', slug: 'moonstone', meaning: '直感' },
  { date: '10月31日', stone: 'オニキス', slug: 'onyx', meaning: '強さ' },

  // 11月
  { date: '11月1日', stone: 'トパーズ', slug: 'topaz', meaning: '友情・誠実' },
  { date: '11月2日', stone: 'ローズクォーツ', slug: 'rose-quartz-meaning', meaning: '愛情' },
  { date: '11月3日', stone: 'シトリン', slug: 'citrine', meaning: '繁栄' },
  { date: '11月4日', stone: 'ガーネット', slug: 'garnet', meaning: '友情' },
  { date: '11月5日', stone: 'トパーズ', slug: 'topaz', meaning: '希望' },
  { date: '11月6日', stone: 'アメジスト', slug: 'amethyst', meaning: '平和' },
  { date: '11月7日', stone: 'サファイア', slug: 'sapphire', meaning: '誠実' },
  { date: '11月8日', stone: 'トパーズ', slug: 'topaz', meaning: '知性' },
  { date: '11月9日', stone: 'ダイヤモンド', slug: 'diamond', meaning: '純粋' },
  { date: '11月10日', stone: 'エメラルド', slug: 'emerald', meaning: '成長' },
  { date: '11月11日', stone: 'トパーズ', slug: 'topaz', meaning: '繁栄' },
  { date: '11月12日', stone: 'ムーンストーン', slug: 'moonstone', meaning: '感受性' },
  { date: '11月13日', stone: 'ターコイズ', slug: 'turquoise', meaning: '守護' },
  { date: '11月14日', stone: 'トパーズ', slug: 'topaz', meaning: '明るさ' },
  { date: '11月15日', stone: 'カーネリアン', slug: 'carnelian', meaning: '活力' },
  { date: '11月16日', stone: 'ラピスラズリ', slug: 'lapis-lazuli', meaning: '真実' },
  { date: '11月17日', stone: 'トパーズ', slug: 'topaz', meaning: '喜び' },
  { date: '11月18日', stone: 'タイガーアイ', slug: 'tigers-eye', meaning: '決断' },
  { date: '11月19日', stone: 'スモーキークォーツ', slug: 'smoky-quartz', meaning: '安定' },
  { date: '11月20日', stone: 'トパーズ', slug: 'topaz', meaning: '幸福' },
  { date: '11月21日', stone: 'ローズクォーツ', slug: 'rose-quartz-meaning', meaning: '優しさ' },
  { date: '11月22日', stone: 'ルビー', slug: 'ruby', meaning: '情熱' },
  { date: '11月23日', stone: 'トパーズ', slug: 'topaz', meaning: '感謝' },
  { date: '11月24日', stone: 'アクアマリン', slug: 'aquamarine', meaning: '清澄' },
  { date: '11月25日', stone: 'ガーネット', slug: 'garnet', meaning: '忠実' },
  { date: '11月26日', stone: 'トパーズ', slug: 'topaz', meaning: '自信' },
  { date: '11月27日', stone: 'オパール', slug: 'opal', meaning: '希望' },
  { date: '11月28日', stone: 'ムーンストーン', slug: 'moonstone', meaning: '直感' },
  { date: '11月29日', stone: 'トパーズ', slug: 'topaz', meaning: '成功' },
  { date: '11月30日', stone: 'シトリン', slug: 'citrine', meaning: '明るさ' },

  // 12月
  { date: '12月1日', stone: 'ターコイズ', slug: 'turquoise', meaning: '幸運・守護' },
  { date: '12月2日', stone: 'ローズクォーツ', slug: 'rose-quartz-meaning', meaning: '愛情' },
  { date: '12月3日', stone: 'ラピスラズリ', slug: 'lapis-lazuli', meaning: '真実' },
  { date: '12月4日', stone: 'ガーネット', slug: 'garnet', meaning: '友情' },
  { date: '12月5日', stone: 'ターコイズ', slug: 'turquoise', meaning: '守護' },
  { date: '12月6日', stone: 'タンザナイト', slug: 'tanzanite', meaning: '高貴・変革' },
  { date: '12月7日', stone: 'アメジスト', slug: 'amethyst', meaning: '平和' },
  { date: '12月8日', stone: 'ターコイズ', slug: 'turquoise', meaning: '保護' },
  { date: '12月9日', stone: 'シトリン', slug: 'citrine', meaning: '繁栄' },
  { date: '12月10日', stone: 'ダイヤモンド', slug: 'diamond', meaning: '純粋' },
  { date: '12月11日', stone: 'ターコイズ', slug: 'turquoise', meaning: '幸福' },
  { date: '12月12日', stone: 'ムーンストーン', slug: 'moonstone', meaning: '感受性' },
  { date: '12月13日', stone: 'タンザナイト', slug: 'tanzanite', meaning: '変革' },
  { date: '12月14日', stone: 'ターコイズ', slug: 'turquoise', meaning: '友情' },
  { date: '12月15日', stone: 'カーネリアン', slug: 'carnelian', meaning: '活力' },
  { date: '12月16日', stone: 'ラピスラズリ', slug: 'lapis-lazuli', meaning: '誠実' },
  { date: '12月17日', stone: 'ターコイズ', slug: 'turquoise', meaning: '旅の守護' },
  { date: '12月18日', stone: 'ルビー', slug: 'ruby', meaning: '情熱' },
  { date: '12月19日', stone: 'スモーキークォーツ', slug: 'smoky-quartz', meaning: '安定' },
  { date: '12月20日', stone: 'ターコイズ', slug: 'turquoise', meaning: '幸運' },
  { date: '12月21日', stone: 'エメラルド', slug: 'emerald', meaning: '希望' },
  { date: '12月22日', stone: 'タンザナイト', slug: 'tanzanite', meaning: '高貴' },
  { date: '12月23日', stone: 'ターコイズ', slug: 'turquoise', meaning: '守護' },
  { date: '12/24日', stone: 'ローズクォーツ', slug: 'rose-quartz-meaning', meaning: '愛情' },
  { date: '12月25日', stone: 'ダイヤモンド', slug: 'diamond', meaning: '永遠' },
  { date: '12月26日', stone: 'タンザナイト', slug: 'tanzanite', meaning: '変化' },
  { date: '12月27日', stone: 'ターコイズ', slug: 'turquoise', meaning: '保護' },
  { date: '12月28日', stone: 'ガーネット', slug: 'garnet', meaning: '忠実' },
  { date: '12月29日', stone: 'アメジスト', slug: 'amethyst', meaning: '誠実' },
  { date: '12月30日', stone: 'ターコイズ', slug: 'turquoise', meaning: '新しい出発' },
  { date: '12月31日', stone: 'ガーネット', slug: 'garnet', meaning: '新年への希望' },
];

function withRakutenAffiliate(url) {
  const afb = process.env.NEXT_PUBLIC_RAKUTEN_AFB;
  if (!afb) return url;
  const sep = url.includes('?') ? '&' : '?';
  return `${url}${sep}scid=af_${encodeURIComponent(afb)}`;
}

export default function BirthdayTable() {
  return (
    <div className="overflow-x-auto my-6">
      <table className="w-full border-collapse text-left text-sm">
        <thead>
          <tr className="bg-amber-100 text-amber-900 border-b border-amber-200">
            <th className="p-3 font-bold">日付</th>
            <th className="p-3 font-bold">誕生日石</th>
            <th className="p-3 font-bold">商品・おすすめ</th>
            <th className="p-3 font-bold">石言葉</th>
          </tr>
        </thead>
        <tbody className="divide-y divide-amber-200">
          {BIRTHDAY_STONES_DATA.map((item, index) => {
            const searchUrl = withRakutenAffiliate(
              `https://search.rakuten.co.jp/search/mall/${encodeURIComponent(item.stone)}+アクセサリー/`
            );

            return (
              <tr key={index} className="hover:bg-amber-50/50 transition-colors">
                <td className="p-3 font-medium text-ink-900 whitespace-nowrap">{item.date}</td>
                <td className="p-3">
                  <a href={`/blog/${item.slug}/`} className="text-amber-700 hover:underline font-bold">
                    {item.stone}
                  </a>
                </td>
                <td className="p-3">
                  <a
                    href={searchUrl}
                    target="_blank"
                    rel="sponsored noopener nofollow"
                    className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-lg bg-rose-50 border border-rose-200 text-rose-700 hover:bg-rose-100 text-xs font-bold transition-all shadow-sm"
                  >
                    <span>🛍️ 楽天で「{item.stone}」を探す</span>
                  </a>
                </td>
                <td className="p-3 text-ink-700">{item.meaning}</td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  );
}